### ISSUE TITLE
Build failing in Pipeline

### ISSUE THREAD

**Issue by teresahoes** [alexruizprado/azure-pipelines-angular-cli-task#8]
hello - i have been using this in Azure pipelines for a few weeks now - has been working great! Now all of a sudden, with no changes to the pipeline, i am getting these errors on ng build --prod.  Note when the same command is run outside of the pipeline (i.e. locally) the prod build runs fine. has anything changed in the last few days w/ this task or do you have suggestions of how to find out more about what is causing the issue?

=======================

Using Angular CLI 9.1.1
Executing ng build  --prod
There was an error: Compiling @angular/core : es2015 as esm2015

##[error]ng build  --prod with error Compiling @angular/core : es2015 as esm2015

There was an error: Compiling @angular/common : es2015 as esm2015

##[error]ng build  --prod with error Compiling @angular/common : es2015 as esm2015
..... etc.

**Comment by Richard809** [comment]
Same thing for me, this may give some context:

- Latest successful build has version 0.0.28.
- As today all builds with version 0.0.32 are failing.

**Comment by alexruizprado** [comment]
Hi, thanks for reaching out.

Looks like a compilation issue with Ivy, I was looking at this open thread https://github.com/angular/components/issues/18637#issuecomment-614383135 and seems very similar. Can you try locally, removing your node_modules folder and performing a fresh install and build with --prod? Also use --verbose=true to see if provides more insights.

I performed some enhancements on the extension for error handling because I received complains that it was not working properly, specially on Linux agents, but the extension really doesn't do anything at the compilation level, it just execute the commands base on your selections and arguments. Could be the build agent is using different package versions so please try the fresh install.

Let me know, happy to help! and if there is an issue with the extension I can make the fix and push an update soon or a rollback.

**Comment by alexruizprado** [comment]
Im able to reproduce the issue locally on a clean angular project
![image](https://user-images.githubusercontent.com/9322343/81592058-5d1adc00-938b-11ea-8782-f881558b8b83.png)
Seems cause by a new version of one of the angular packages. Funny thing is that the second run works fine. Im still investigating.

**Comment by teresahoes** [comment]
okay thanks so much for your help!!

**Comment by alexruizprado** [comment]
I just pushed a new release of the extension that should fix the issue. Please make some small change in the pipeline to force and update on the extension step, anything will work, a step title change for example. It should be 0.0.33.
![image](https://user-images.githubusercontent.com/9322343/81602014-dae5e400-9399-11ea-985f-1cfa3690c9e3.png)

**Comment by teresahoes** [comment]
yay success! thanks so much for such a quick response  and for your work on this package :)

**Comment by alexruizprado** [comment]
Thanks for your feedback!
